services:
  service_a:
    build: ./service_a
    container_name: service_a
    networks:
      - micro_net

  service_b:
    build: ./service_b
    container_name: service_b
    ports:
     - "5002:5002"
    depends_on:
     - service_a
    networks:
     - micro_net

networks:
  micro_net: